### ISSUE TITLE
Test Runtime Error

### ISSUE THREAD

**Issue by DKandrew** [CharlesShang/DCNv2#10]
Give following error on a freshly cloned repo

```
error in modulated_deformable_im2col_cuda: a PTX JIT compilation failed
Traceback (most recent call last):
  File "test.py", line 255, in <module>
    example_dconv()
  File "test.py", line 177, in example_dconv
    targert.data.uniform_(-0.01, 0.01)
RuntimeError: Creating MTGP constants failed. at /opt/conda/conda-bld/pytorch_1549630534704/work/aten/src/THC/THCTensorRandom.cu:35
```
Does anyone encounter this issue? 
I am using PyTorch 1.0.0 and CUDA 10.

**Comment by Marigod98** [comment]
Did you ever figure this out? Also having the same issue
