### ISSUE TITLE
Has anyone met this error when running test.py: "RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`"

### ISSUE THREAD

**Issue by ltqqq** [CharlesShang/DCNv2#112]
When installing DCN, I didn't see any errors.
Then I ran testcpu.py, the code works fine: 

> torch.Size([2, 64, 128, 128])
torch.Size([20, 32, 7, 7])
torch.Size([20, 32, 7, 7])
torch.Size([20, 32, 7, 7])
0.971507, 1.943014
0.971507, 1.943014
Zero offset passed
/disk1/ltq/anaconda3/envs/pytorch171/lib/python3.8/site-packages/torch/autograd/gradcheck.py:301: UserWarning: The {}th input requires gradient and is not a double precision floating point or complex. This check will likely fail if all the inputs are not of double precision floating point or complex.
  warnings.warn(
check_gradient_dpooling: True
check_gradient_dconv:  True

But when I run test.py or testcuda.py, there will be the following error:

> Traceback (most recent call last):
  File "test.py", line 285, in <module>
    example_dconv()
  File "test.py", line 203, in example_dconv
    error.backward()
  File "/disk1/ltq/anaconda3/envs/pytorch171/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/disk1/ltq/anaconda3/envs/pytorch171/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
  File "/disk1/ltq/anaconda3/envs/pytorch171/lib/python3.8/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/disk1/ltq/anaconda3/envs/pytorch171/lib/python3.8/site-packages/torch/autograd/function.py", line 210, in wrapper
    outputs = fn(ctx, *args)
  File "/disk1/ltq/DCNv2/dcn_v2.py", line 51, in backward
    grad_input, grad_offset, grad_mask, grad_weight, grad_bias = _backend.dcn_v2_backward(
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
段错误 (核心已转储)

This problem bothered me for a day, and I didn’t see other issues mentioning this kind of error.

Here's my environment:
PyTorch==1.7.1
CUDA==10.1
Python==3.8
and my GPU is TITAN Xp.

Does anyone know how to fix this???

**Comment by USCLXL** [comment]
Hi，Have you solved this problem？
