### ISSUE TITLE
DCNv2 undefined symbol

### ISSUE THREAD

**Issue by caleballen** [CharlesShang/DCNv2#117]
Hi there,
I can build the extension successfully but upon testing with either test file I get the following error. This would suggest the build was not successful.

```
python testcuda.py                                                                                                                                                                                                    
Traceback (most recent call last):
  File "testcuda.py", line 11, in <module>
    from dcn_v2 import dcn_v2_conv, DCNv2, DCN
  File "/home/david/CenterTrack/src/lib/model/networks/DCNv2/dcn_v2.py", line 13, in <module>
    import _ext as _backend
ImportError: /home/david/CenterTrack/src/lib/model/networks/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
```

I am running on Arch Linux x64 in a conda environment with pytorch==1.4.0 torchvision==0.5.0 and cudatoolkit=10.1.
[Build logs](https://pastebin.com/Qpkx0qu3)

Any pointers on what could be causing this? I've tried many different version combinations from [here](https://pytorch.org/get-started/previous-versions/).

**Comment by lwCVer** [comment]
> 您好， 我可以成功构建扩展，但是在使用任一测试文件进行测试时，我收到以下错误。这表明构建不成功。
> 
> ```
> python testcuda.py                                                                                                                                                                                                    
> Traceback (most recent call last):
>   File "testcuda.py", line 11, in <module>
>     from dcn_v2 import dcn_v2_conv, DCNv2, DCN
>   File "/home/david/CenterTrack/src/lib/model/networks/DCNv2/dcn_v2.py", line 13, in <module>
>     import _ext as _backend
> ImportError: /home/david/CenterTrack/src/lib/model/networks/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
> ```
> 
> 我在 pytorch==1.4.0 torchvision==0.5.0 和 cudatoolkit=10.1 的 conda 环境中运行 Arch Linux x64。 [构建日志](https://pastebin.com/Qpkx0qu3)
> 
> 关于可能导致这种情况的任何指示？我从[这里](https://pytorch.org/get-started/previous-versions/)尝试了许多不同的版本组合。

I also met the same problem. Have you solved this problem now

**Comment by lwCVer** [comment]
> Hi there, I can build the extension successfully but upon testing with either test file I get the following error. This would suggest the build was not successful.
> 
> ```
> python testcuda.py                                                                                                                                                                                                    
> Traceback (most recent call last):
>   File "testcuda.py", line 11, in <module>
>     from dcn_v2 import dcn_v2_conv, DCNv2, DCN
>   File "/home/david/CenterTrack/src/lib/model/networks/DCNv2/dcn_v2.py", line 13, in <module>
>     import _ext as _backend
> ImportError: /home/david/CenterTrack/src/lib/model/networks/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
> ```
> 
> I am running on Arch Linux x64 in a conda environment with pytorch==1.4.0 torchvision==0.5.0 and cudatoolkit=10.1. [Build logs](https://pastebin.com/Qpkx0qu3)
> 
> Any pointers on what could be causing this? I've tried many different version combinations from [here](https://pytorch.org/get-started/previous-versions/).

I also met the same problem. Have you solved this problem now

**Comment by caleballen** [comment]
I have solved the problem. As I was building DCN to run [this](https://github.com/xingyizhou/CenterTrack/blob/master/readme/INSTALL.md), I reinstalled my system as per their environment using Ubuntu 18.04 LTS, Anaconda Python 3.6, CUDA 10.0, and PyTorch v1.0. In this environment DCN built correctly.

As for running it on Arch, I believe the undefined symbol could be due to Arch's modern GCC version, installing an older version may work but in my case it was faster to reload the system with Ubuntu.

**Comment by lwCVer** [comment]
> I have solved the problem. As I was building DCN to run [this](https://github.com/xingyizhou/CenterTrack/blob/master/readme/INSTALL.md), I reinstalled my system as per their environment using Ubuntu 18.04 LTS, Anaconda Python 3.6, CUDA 10.0, and PyTorch v1.0. In this environment DCN built correctly.
> 
> As for running it on Arch, I believe the undefined symbol could be due to Arch's modern GCC version, installing an older version may work but in my case it was faster to reload the system with Ubuntu.

thank you

**Comment by poochat** [comment]
I have successfully resolved this bug on 4060TI. The screenshot is as follows, and my email is: kangchou2099@126.com。

![Image](https://github.com/user-attachments/assets/9fd5e39a-cf26-4896-9584-26a71836f53f)
