### ISSUE TITLE
run in 4060ti

### ISSUE THREAD

**Issue by bdpk123** [CharlesShang/DCNv2#142]
Thanks for your work.
How do I run DCNv2 in 40s NVIDIA?

**Comment by poochat** [comment]
```bash

clude/TH -I/opt/conda/envs/pytorch17/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/opt/conda/envs/pytorch17/include/python3.7m -c /data/CenterFusion/src/lib/model/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp -o build/temp.linux-x86_64-cpython-37/data/CenterFusion/src/lib/model/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 556, in build_extension
    depends=ext.depends,
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 418, in unix_wrap_single_compile
    cflags = unix_cuda_flags(cflags)
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 395, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags) +
  File "/opt/conda/envs/pytorch17/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1438, in _get_cuda_arch_flags
    raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
ValueError: Unknown CUDA arch (8.9) or GPU not supported
(pytorch17) root@ubuntu-Z790:/data/CenterFusion/src/lib/model/networks/DCNv2# rm -rf build/
(pytorch17) root@ubuntu-Z790:/data/CenterFusion/src/lib/model/networks/DCNv2# conda env config vars set TORCH_CUDA_ARCH_LIST="8.9"
To make your changes take effect please reactivate your environment
(pytorch17) root@ubuntu-Z790:/data/CenterFusion/src/lib/model/networks/DCNv2# conda env config vars set TORCH_CUDA_ARCH_LIST="8.0"
To make your changes take effect please reactivate your environment
(pytorch17) root@ubuntu-Z790:/data/CenterFusion/src/lib/model/networks/DCNv2# 


```

**Comment by poochat** [comment]
> Thanks for your work. How do I run DCNv2 in 40s NVIDIA?

I have successfully solved this problem. The following is a screenshot（4060TI）：

![Image](https://github.com/user-attachments/assets/3888c6d9-f005-4641-990f-dd9cdebee343)

**Comment by poochat** [comment]
> Thanks for your work. How do I run DCNv2 in 40s NVIDIA?

I have successfully resolved this bug on 4060TI. The screenshot is as follows, and my email is: kangchou2099@126.com。

![Image](https://github.com/user-attachments/assets/9fd5e39a-cf26-4896-9584-26a71836f53f)
