### ISSUE TITLE
erro when test

### ISSUE THREAD

**Issue by Hrhythm** [CharlesShang/DCNv2#15]
I do the make.sh successfully, but when I do python test.py in DCVv2, I met this error:
Traceback (most recent call last):
File "test.py", line 11, in 
from dcn_v2 import dcn_v2_conv, DCNv2, DCN
File "/home/data/CenterNet-master/src/lib/models/networks/DCNv2-master/dcn_v2.py", line 13, in 
import _ext as _backend
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

**Comment by shenyingying** [comment]
@Hrhythm have you solved the problem!
