### ISSUE TITLE
No  module named  _ext    in  dcn_v2.py

### ISSUE THREAD

**Issue by heartInsert** [CharlesShang/DCNv2#24]
When  I  successful     sh   'make.sh', I   got  this  import  error ,  is  there  anyone  who   have  met  the  same  problem  before?

**Comment by heartInsert** [comment]
@CharlesShang   Thanks  for  reply

**Comment by heartInsert** [comment]
By  the  way  ,   my  pytorch  version  is  1.1.0 ,  does  it   affects  the result  that  should  I   dowdgrade  it  to   1.0.0?

**Comment by maminglang1991** [comment]
me too...

**Comment by zzzzwj** [comment]
Me too. When I run make.sh on Ubuntu 18.04 with cuda 9.0, it worked while run on Ubuntu 16.04 with cuda 7.5, it failed. I'm confused about it. I also met another problem:
`ImportError:/home/xxx/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE`.

**Comment by yijingru** [comment]
import _ext as _backend
ModuleNotFoundError: No module named '_ext'

**Comment by kevin-collins** [comment]
If someone has solved this problem,please tell me！！！！！！！！！！！！！！

**Comment by kevin-collins** [comment]
> When I successful sh 'make.sh', I got this import error , is there anyone who have met the same problem before?

Can you tell me how do you successful sh 'make.sh'?need special configuration?and are you running it under Window10_64?

**Comment by heartInsert** [comment]
> > When I successful sh 'make.sh', I got this import error , is there anyone who have met the same problem before?
> 
> Can you tell me how do you successful sh 'make.sh'?need special configuration?and are you running it under Window10_64?

Yes,I run  it  in  window10_64,  you  must  change  some  configuration,   
`https://github.com/xingyizhou/CenterNet/issues/7`
fllow  this  issues  , look  carefully

**Comment by kevin-collins** [comment]
> > > When I successful sh 'make.sh', I got this import error , is there anyone who have met the same problem before?
> > 
> > 
> > Can you tell me how do you successful sh 'make.sh'?need special configuration?and are you running it under Window10_64?
> 
> Yes,I run it in window10_64, you must change some configuration,
> `https://github.com/xingyizhou/CenterNet/issues/7`
> fllow this issues , look carefully

Thanks！！！

**Comment by yuanjunchai** [comment]
Me too

**Comment by yuanjunchai** [comment]
> By the way , my pytorch version is 1.1.0 , does it affects the result that should I dowdgrade it to 1.0.0?

Have you solved the problem?

**Comment by SkyeLu** [comment]
Has any one solved it? I met the same problem.

**Comment by Fighting-JJ** [comment]
python 3.6 works well

**Comment by ntoxeg** [comment]
I just invoked `python setup.py install` (in a Conda environment) and this solved the problem.

**Comment by huohuotm** [comment]
> `ImportError:/home/xxx/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE`.

@zzzzwj  did you fix this problem?

**Comment by zzzzwj** [comment]
> > `ImportError:/home/xxx/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE`.
> 
> @zzzzwj did you fix this problem?

Sorry, I didn't. I switched to another machine after that. But when I try to run it again, it seems work now. All I did is removing the _ext.cpythonxxxx and recompiling it. But the environment may be not the same as  it was when I raised this issue.

**Comment by IrisDinge** [comment]
i fix this bug by 
1. delete whole package
2. shift conda env to pytorch 0.4.0, python 3.6, cuda 9.0, 2080Ti(it doesn't matter I guess)
3. cd DCNv2
4. git checkout pytorch_0.4(then u will check directory has been changed)
5. ./make.sh
6. python test.py
7. run

Good Luck guys;)

**Comment by dankydev** [comment]
> i fix this bug by
> 
> 1. delete whole package
> 2. shift conda env to pytorch 0.4.0, python 3.6, cuda 9.0, 2080Ti(it doesn't matter I guess)
> 3. cd DCNv2
> 4. git checkout pytorch_0.4(then u will check directory has been changed)
> 5. ./make.sh
> 6. python test.py
> 7. run
> 
> Good Luck guys;)

This is not the way it should be solved, since this error is supposed to appear when the user tries to migrate the network to Pytorch >= 1.0. 
@CharlesShang can you provide a valid and definitive solution please? I followed the instructions, i launched `python setup.py install` and `./make.sh` but it keeps saying `ModuleNotFoundError: No module named '_ext'`

**Comment by shuyu888** [comment]
ModuleNotFoundError: No module named '_ext'

**Comment by moligaCUG** [comment]
> > i fix this bug by
> > 
> > 1. delete whole package
> > 2. shift conda env to pytorch 0.4.0, python 3.6, cuda 9.0, 2080Ti(it doesn't matter I guess)
> > 3. cd DCNv2
> > 4. git checkout pytorch_0.4(then u will check directory has been changed)
> > 5. ./make.sh
> > 6. python test.py
> > 7. run
> > 
> > Good Luck guys;)
> 
> This is not the way it should be solved, since this error is supposed to appear when the user tries to migrate the network to Pytorch >= 1.0. @CharlesShang can you provide a valid and definitive solution please? I followed the instructions, i launched `python setup.py install` and `./make.sh` but it keeps saying `ModuleNotFoundError: No module named '_ext'`

when i run "python setup.py install", the error was:

(TLTDMOT) F:\CUG3.2\Trajectory-Long-tail-Distribution-for-MOT-master\src>bash make.sh
running build
running build_ext
E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\torch\utils\cpp_extension.py:499: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\torch\utils\cpp_extension.py:384: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building '_ext' extension
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    setup(
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\dist.py", line 989, in run_command
    super().run_command(command)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
    self.run_command(cmd_name)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\dist.py", line 989, in run_command
    super().run_command(command)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
    _build_ext.run(self)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\torch\utils\cpp_extension.py", line 870, in build_extensions
    build_ext.build_extensions(self)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\Cython\Distutils\build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 572, in build_extension
    self.compiler.link_shared_object(
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\ccompiler.py", line 752, in link_shared_object
    self.link(
  File "E:\Download_google_or_edge\anaconda\app\envs\TLTDMOT\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 498, in link
    build_temp = os.path.dirname(objects[0])
IndexError: list index out of range

have you ever met this problem? And after that, did you successed in solving "_ext" problem?
