### ISSUE TITLE
torch/extension.h: No such file or directory

### ISSUE THREAD

**Issue by Cuiyirui** [CharlesShang/DCNv2#6]
When I compiling in my Ubuntu system. It released an error, said:
DCNv2-master/src/cpu/vision.h:2:29: fatal error: torch/extension.h: No such file or directory
There is not file named "torch" in above mentioned path, How can I solve the question

**Comment by miaoshuyu** [comment]
i have the same problem,have you solved it?

**Comment by rxqy** [comment]
Which version of pytorch are you using?
If you are using pytorch 0.4, you need to git checkout to the 0.4 branch
[https://github.com/CharlesShang/DCNv2#note](url)

**Comment by butyuhao** [comment]
I‘m using the 1.0.1,and get the following problem. Very confusing.
 fatal error: cusparse.h: No such file or directory

**Comment by hailuo0112** [comment]
> Which version of pytorch are you using?
> If you are using pytorch 0.4, you need to git checkout to the 0.4 branch
> [https://github.com/CharlesShang/DCNv2#note](url)

I‘m using the pytorch1.0, and get the same problem.

**Comment by hailuo0112** [comment]
> When I compiling in my Ubuntu system. It released an error, said:
> DCNv2-master/src/cpu/vision.h:2:29: fatal error: torch/extension.h: No such file or directory
> There is no file named "torch" in above mentioned path, How can I solve the question

have you solved it?

**Comment by omrysendik** [comment]
Same error here too. I am also using 1.0.1.

**Comment by liuli2017** [comment]
I solved this problem. 
I run shell under pytorch 0.4, which caused this error. 
Because i forgot to activate my conda environment, pytorch 1.01.

**Comment by singal95** [comment]
solved with pytorch 1.4.0

**Comment by gopalkumr** [comment]
@singal95  can you Please help me, I installed pytorch=1.4.0 but now i'm getting diffrent error 

`Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
  File "E:\anaconda\envs\py38\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed while importing _C: The specified module could not be found.`

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/91552766/233054192-5c71f10f-ac46-443a-bcdd-4bf133d55204.png">

**Comment by 8946ben** [comment]
oh, i meet this problem, my torch version is  0,4,1, so i need `git checkout pytorch_0.4` before `make.sh`
