### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by spades10** [CharlesShang/DCNv2#64]
hello, Auther, Thank you for wonderful work! Rencently, I used make.sh to build, but I  get RuntimeError.
Here is my environment: Ubuntu 16.04 + pytorch 1.5 + cuda 10.2 + python 3.7

running build
running build_ext
building '_ext' extension
Emitting ninja build file /home/yix/git/DCNv2/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/local/cuda-10.2/bin/nvcc -DWITH_CUDA -I/home/yix/git/DCNv2/src -I/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/include -I/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/include/TH -I/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/include/python3.7m -c -c /home/yix/git/DCNv2/src/cuda/dcn_v2_cuda.cu -o /home/yix/git/DCNv2/build/temp.linux-x86_64-3.7/home/yix/git/DCNv2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home/yix/git/DCNv2/build/temp.linux-x86_64-3.7/home/yix/git/DCNv2/src/cuda/dcn_v2_cuda.o 
/usr/local/cuda-10.2/bin/nvcc -DWITH_CUDA -I/home/yix/git/DCNv2/src -I/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/include -I/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/include/TH -I/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/include/python3.7m -c -c /home/yix/git/DCNv2/src/cuda/dcn_v2_cuda.cu -o /home/yix/git/DCNv2/build/temp.linux-x86_64-3.7/home/yix/git/DCNv2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
/home/yix/git/DCNv2/src/cuda/dcn_v2_cuda.cu(107): error: identifier "THCState_getCurrentStream" is undefined

/home/yix/git/DCNv2/src/cuda/dcn_v2_cuda.cu(279): error: identifier "THCState_getCurrentStream" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00002554_00000000-6_dcn_v2_cuda.cpp1.ii".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/yix/anaconda3/envs/py3.7+torch1.5+10.2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

How to solve this problem ?

**Comment by danielzgsilva** [comment]
I am getting same issue

**Comment by spades10** [comment]
I figure it out from https://github.com/lbin/DCNv2/tree/pytorch_1.5

you just need to clone it and follow the README.md

**Comment by shafu0x** [comment]
I get the same error.

**Comment by keshavoct98** [comment]
Downgrading pytorch to 1.4.0 and torchvision to 0.5.0 resolved the error for me.

**Comment by spades10** [comment]
problems solved

**Comment by shaojiestar** [comment]
what did you do to solve this problem,bro?
please help me 
thank you

**Comment by NoCodeAvaible** [comment]
@shaojiestar I would tag this dude so that he is getting a notification:)
