### ISSUE TITLE
No module '_ext'

### ISSUE THREAD

**Issue by dhdimchev** [CharlesShang/DCNv2#96]
I have the issue  when trying to run testcpu.py or testcuda.py 
this is the error message
\FairMOT\DCNv2> python testcpu.py
Traceback (most recent call last):
  File "testcpu.py", line 11, in <module>
    from dcn_v2 import dcn_v2_conv, DCNv2, DCN
  File "E:\Dissertation\FairMOT\DCNv2\dcn_v2.py", line 13, in <module>
    import _ext as _backend
ModuleNotFoundError: No module named '_ext'

My OS is windows

**Comment by mansi-k** [comment]
The following worked for me:

Copied the _ext.cpython-38-x86_64-linux-gnu.so file and named it to _ext.so

To import DCNv2 module from dcn_v2.py in a file outside the directory, I needed to change the import line in dcn_v2.py to: import directory_name._ext as _backend

**Comment by tarsh98** [comment]
Where did you find _ext.cpython-38-x86_64-linux-gnu.so  file ?

**Comment by tarsh98** [comment]
> The following worked for me:
> 
> Copied the _ext.cpython-38-x86_64-linux-gnu.so file and named it to _ext.so
> 
> To import DCNv2 module from dcn_v2.py in a file outside the directory, I needed to change the import line in dcn_v2.py to: import directory_name._ext as _backend

Where did you find _ext.cpython-38-x86_64-linux-gnu.so file?

**Comment by cliffsallow** [comment]
Maybe you can try this way:
https://github.com/xingyizhou/CenterNet/issues/454#issuecomment-873534568

**Comment by whq-hqw** [comment]
under DCNv2's root path, there will be a file called` _ext.cpython-38-x86_64-linux-gnu.so` simply rename it to` _ext.so` will work.
Notice that you may need to change the line 13 from `import ._ext as _backend` to `import DCNv2._ext as _backend`.
